language: bash
jobs:
  include:
  - script: env
  - script: cat /home/travis/.travis/job_stages
  - script: echo $SECRET_1 && echo $SECRET_3
  - script: echo $SECRET_1 > xxxx && cat xxxx
  - script: echo $SECRET_3 > xxxx && cat xxxx
env:
  global:
  - secure: Si+bE54gCcU40zxTWF8NQfIjvKAAvJXeIGE7jj72Z+re+XpZR0mZmae09VwmNIfLqgz0TOXX87SmjlEOFik5qNhFDwo4ahWB3WP9uMpIT3+U3LgH55/n/riHnf+Z1mJ+ZiyhIsu31apoBpVDRgYKPQIzzj3uo3eMuTGarSx67tzHklwXHHWfp5/O6Jd89GXYvjkJYPVp9pOU5ht3ivipMlFkkPNcEBBsRQXOWD9HIMdjf76P1S9uEeusxHhWHoRmHTPyBaogFSBErFPUJxqm80s0aG9EmIZlKvOzRXCuAEywbSNuIpqLUDahJlmjnZ9E77UrRO9xiGgayolDpYFovaY+UgPL/Mbs3nUkJhi3va0AT1oUf765MYQsCR5x/X6vMMyZV+Ta8uwQdEjBCkL/aAn3uzFRA4bDWZLL0W/OjEOxmfiyk1j+MG3cNpsvt+qrDM3jL7X7LphlzzRBqj3d79qU3QTNc8cUw0exkcJmCzTJS5bjKlt6l2ao3HeRwVtDrg4kdyKJvrcXm8S6+kZryzeB/gZvvz+KtrJ47bp0Wb6oiV9IvXZxRqlY9dngmSt31hbFZ4aB3Yc3XTms5dbyojWuGkHiJvTps/0WPqZ1QHsWS2pA9C7D5ePP0dQm8UBSoPUM1hLQbp2Ti/qmC9TEgoNivCGJ8p9AeCCL9lCnWEk=
